apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacitycapstone-nextcloud
  labels:
    app: udacitycapstone-nextcloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacitycapstone-nextcloud
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: udacitycapstone-nextcloud
    spec:
      containers:
        - image: 627513304485.dkr.ecr.us-west-2.amazonaws.com/udacitycapstone-nextcloud:latest
          name: udacitycapstone-nextcloud
          ports:
            - containerPort: 80
              name: http-server
      imagePullSecrets:
        - name: ecr-secret
