apiVersion: v1
kind: Service
metadata:
  name: udacitycapstone-nextcloud
  labels:
    name: udacitycapstone-nextcloud
spec:
  selector:
    app: udacitycapstone-nextcloud
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      protocol: TCP
