apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::251557857946:user/jenkins
      username: jenkins
      groups:
        - system:masters
  mapRoles: |
    - rolearn: arn:aws:iam::627513304485:role/UdacityDevOpsNanodegreeCapStone-K-NodeInstanceRole-1TZJ78AIV3F4
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
