apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::627513304485:user/sharat
      username: sharat
      groups:
        - system:masters
  mapRoles: |
    - rolearn: arn:aws:iam::627513304485:role/UdacityDevOpsNanodegreeCapStone-K-NodeInstanceRole-1MX9T65YBHF8F
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
